// File generated by FlutterFire CLI — replace via `flutterfire configure`.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not a target for Polad.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  /// Placeholders. Run `flutterfire configure` before a production Firebase build.
  static const android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:android:replace',
    messagingSenderId: '000000000000',
    projectId: 'polad-family-fund',
    storageBucket: 'polad-family-fund.appspot.com',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:replace',
    messagingSenderId: '000000000000',
    projectId: 'polad-family-fund',
    storageBucket: 'polad-family-fund.appspot.com',
    iosBundleId: 'ir.polad.polad',
  );
}
